name: Run Google Drive Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.x'

     - name: Install Python dependencies
       run: |
         python -m pip install --upgrade pip
         pip install google-api-python-client google-auth google-auth-oauthlib

     - name: Install FFmpeg and all related packages
       run: |
         sudo apt-get update
         sudo apt-get install -y ffmpeg libavcodec-extra libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libpostproc-dev libswscale-dev libswresample-dev

     - name: Verify FFmpeg installation
       run: ffmpeg -version

     - name: Run script
       run: python vid-t.py
       
     - name: Commit and push uploaded_files.txt
       run: |
           if [ -f "uploaded_files.txt" ]; then
             git config --global user.name "GitHub Bot"
             git config --global user.email "github-bot@example.com"
             git add uploaded_files.txt
             git commit -m "Update uploaded_files.txt"
             git push
           else
            echo "uploaded_files.txt not found. Skipping commit."
           fi

